### ISSUE TITLE
Inspect.Heap: ClrInformationNotFoundException when using ManualResetValuesTaskSourceCore

### ISSUE THREAD

**Issue by jasper-d** [ashmind/SharpLab#1206]
When passing an object that has a field of type `ManualResetValueTaskSourceCore<T>` (with a concrete `T`) to `Inspect.Heap`, SharpLab runtime fails with a `SharpLab.Container.Runtime.ClrInformationNotFoundException`. Source of the exception appears to be here: 
https://github.com/ashmind/SharpLab/blob/08734b02742ff866287b1b6b25455cfeb4c4515a/source/Container/Runtime/MemoryBytesInspector.cs#L109-L110
This happens both in Debug and Release configuration, using x64 as well as latest main (`main (28 Sep 2022)` as of writing).

The issue does not reproduce when using `ReadOnlySequence<byte>` instead of MRVTSC.

## Repro:
[Sharplab link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQAYACCgRgFYA6AZQhyjBgGcBuALAAoYXgCGAW14AHMdxoAlGNKgRBIoRQBMAZhoBvYTWN0tWw0JNWaAWQCeAeWAArGGAw0JwGgF4aeGAB3W0cXNwwACgBKPmtjIziaAEk8Hmlw5gAJGDFpCK8YhOMAX2FSjQBLPAwYKHEAGxoeHPqYQlMQp1d3GmELKxUKgDcxGtsxPBwxeqVmjAA1aZwYCiR2Tm4AYWgYAB5gCAh6gD4aAH1IWF9/IPHJ6dmYBaWVtY4uGG3YfcOT6PVykA===)

C#:

```csharp
using System.Threading.Tasks.Sources;

namespace Repro;

public static class Program {
    public static void Main(){
        MyObject mb = new MyObject();       
        Inspect.Heap(mb);
    }
}

internal sealed class MyObject 
{
    private ManualResetValueTaskSourceCore<bool> _core = new ManualResetValueTaskSourceCore<bool>();
}
```

Error:

```
SharpLab.Container.Runtime.ClrInformationNotFoundException: Could not get type for field _continuation.
   at SharpLab.Container.Runtime.MemoryBytesInspector.CreateLabelsFromType(ClrType objectType, UInt64 objectAddress, UInt64 offsetBase, ValueTuple`2 first) in D:\a\SharpLab\SharpLab\source\Container\Runtime\MemoryBytesInspector.cs:line 110
   at SharpLab.Container.Runtime.MemoryBytesInspector.CreateLabelsFromType(ClrType objectType, UInt64 objectAddress, UInt64 offsetBase, ValueTuple`2 first) in D:\a\SharpLab\SharpLab\source\Container\Runtime\MemoryBytesInspector.cs:line 87
   at SharpLab.Container.Runtime.MemoryBytesInspector.InspectHeap(Object object) in D:\a\SharpLab\SharpLab\source\Container\Runtime\MemoryBytesInspector.cs:line 38
   at Inspect.Heap(Object object) in D:\a\SharpLab\SharpLab\source\Runtime\Inspect.cs:line 7
   at Repro.Program.Main()
```
Sometimes there is no stack trace but only this:
> #(Container crashed, next container will be available in 15 seconds)

**Comment by ashmind** [comment]
Interesting! Thanks for a detailed report. I will be keen to take a look when I have a moment.
