### ISSUE TITLE
SharpLab throws OverflowException on disassembling under x86 .NET Framework

### ISSUE THREAD

**Issue by nthalpy** [ashmind/SharpLab#1253]
SharpLab is currently throwing an OverflowException when try to disassemble with the x86 .NET Framework. Other frameworks, such as .NET Core and the x64 .NET Framework, are working fine. Full exception message is

```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at SharpLab.Server.Decompilation.JitAsmDecompilerBase.DisassembleAndWrite(MethodJitResult result, ClrRuntime runtime, ArchitectureMode architecture, Translator translator, Reference`1 methodAddressRef, TextWriter writer)
   at SharpLab.Server.Decompilation.JitAsmDecompilerBase.Decompile(CompilationStreamPair streams, TextWriter codeWriter) in D:\a\SharpLab\SharpLab\source\NetFramework\Server\Decompilation\JitAsmDecompilerBase.cs:line 39
   at SharpLab.Server.MirrorSharp.SlowUpdate.WriteResult(IFastJsonWriter writer, Object result, IWorkSession session) in D:\a\SharpLab\SharpLab\source\NetFramework\Server\MirrorSharp\SlowUpdate.cs:line 138
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<SendSlowUpdateAsync>d__5.MoveNext() in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext() in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__16.MoveNext() in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__15.MoveNext() in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 54
```

It was working well when I decompiled some codes under x86 .NET Framework at Feb 4th, so it seems to have broken recently.

Here is repro on sharplab.io: https://sharplab.io/#v2:EYLgdgpgLgZgHgGiiAhgZwLYB8ACAmARgFgAoUnAZgAJ8aCB2Ugb1KrZrz1fZZPaoC+pAUA=

**Comment by ashmind** [comment]
Interesting! The link is working now, and I think there were no releases in February either. I am thinking it might be caused by a specific memory address that code was not able to handle, and so the issues is random depending on the memory situation -- I'll take a look when I have a moment.
