### ISSUE TITLE
JIT Asm cant be generated

### ISSUE THREAD

**Issue by AlmightyLks** [ashmind/SharpLab#1269]
As soon as I include my linq, it starts breaking, compare

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgBkBLAOwEcBuGvSbkUA6gEhJkwQGYmpYQHYaAbxriypdWonjOuDAB5uGAHwMuAV3zAYUXAwC8FmAHcG+oydMAKAJQMKgzoDHRowTLh5KThDORhDDGJ4ShJAKxpSOFyAL5i4jk0OUA
and
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgBkBLAOwEcBuGvSbkUA6gEhJkwQGYmpYQHYaAbxriypdWonjOuDAB5uGAHwMuAV3zAYUXAwC8FmAHcG+oydMAKAJQMKgzoDHRowTLh5KThDORhDDGJ4ShJAKxpSOFyAL5iklY2drgsAOoAFnYwPghO5uriOlLMAJw+AESulbDtfvmSxIoMtQCkiU7OdP05fg3iLADCEJZcGDV1c+IM200D5G3tkCsYvf1S20xDtYYMaWcz+Tk0OUA

In text form:
This works
```cs
using System;
using System.Linq;
using System.Collections.Generic;
					
public class Program
{
	public static void Main()
	{
		List<int> numbers = new List<int>() { 4, 0, 43, 12,  10, 2, 2, 42, 556, 3 };
	}
}
```

This breaks:
```cs
using System;
using System.Linq;
using System.Collections.Generic;
					
public class Program
{
	public static void Main()
	{
		List<int> numbers = new List<int>() { 4, 0, 43, 12,  10, 2, 2, 42, 556, 3 };
		numbers.Where(x => 
		{
			Console.WriteLine("where");
			return x % 2 == 0;
		})
			.Count(x =>
				   {
			Console.WriteLine("count");
					   return x < 5;
			});
	}
}
```

When looking at the JIT Asm output, you can see the following exception:
```
System.NotSupportedException: Type Program+<>c has a static constructor, which is not supported by SharpLab JIT decompiler.
   at SharpLab.Server.Decompilation.JitAsmDecompiler.EnsureNoJitSideEffects(Assembly assembly) in D:\a\SharpLab\SharpLab\source\Server\Decompilation\JitAsmDecompiler.cs:line 76
   at SharpLab.Server.Decompilation.JitAsmDecompiler.Decompile(CompilationStreamPair streams, TextWriter codeWriter, IWorkSession session) in D:\a\SharpLab\SharpLab\source\Server\Decompilation\JitAsmDecompiler.cs:line 57
   at SharpLab.Server.MirrorSharp.SlowUpdate.WriteResult(IFastJsonWriter writer, Object result, IWorkSession session) in D:\a\SharpLab\SharpLab\source\Server\MirrorSharp\SlowUpdate.cs:line 175
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.SendSlowUpdateAsync(IReadOnlyList`1 diagnostics, WorkSession session, Object extensionResult, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 74
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 39
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 118
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 73
```

**Comment by ashmind** [comment]
Thanks for reporting! JIT is something I do want to improve in, including this limitation.
However for now this is not supported, for application security reasons.
