### ISSUE TITLE
Allow Microsoft.VisualBasic.CompilerServices.Conversions in Unbreakable

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#178]
When I [try to Run the following simple VB code](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBsQDdhJiBBXAOyQBMQBqAHwEkwAHAewRigAIBlAT1jjAFgAoALL1ieFHBYAFBPQDmCCH34sV7PMBaCIASwIAKAJQDVJlgGF6BKPXEA6AOoJt8ADK64egESeWAMhYAYhAoUHBGyqoAogTEasAC0bHCouJAA):

```vb.net
Imports System
Module Program
    Sub Main()
        Console.WriteLine("" & False)
    End Sub
End Module
```

I get the exception:

```
Unbreakable.AssemblyGuardException: Type Microsoft.VisualBasic.CompilerServices.Conversions is not allowed.
   at Unbreakable.Internal.CecilApiValidator.EnsureAllowed(TypeReference type, String memberName)
   at Unbreakable.Internal.CecilApiValidator.ValidateMemberReference(MemberReference reference)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, CecilApiValidator apiValidator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, CecilApiValidator apiValidator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(Stream assemblyStream, Stream symbolStream, IWorkSession session)
   at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

As far as I understand it, fixing this shouldn't be a fascinating transition, is should be just a matter of adding the `Microsoft.VisualBasic.CompilerServices.Conversions` type to [SafeDefaultApiPolicy](https://github.com/ashmind/Unbreakable/blob/master/[Core]/Internal/SafeDefaultApiPolicy.cs) in Unbreakable.

**Comment by ashmind** [comment]
@svick Thanks for your report!
Yes, that's easy to add, and Visual Basic libraries are currently in the extended policy (in SharpLab), so I don't even need a new Unbreakable.

**Comment by ashmind** [comment]
I'm going to allow a subset that does not need extra review (which covers your case), please add a ticket if you run into something else.

https://github.com/ashmind/SharpLab/blob/edge/source/Server/Execution/Internal/ApiPolicySetup.PolicyReport.txt#L434-L459

(not released yet)

**Comment by ashmind** [comment]
Fixed in default (https://sharplab.io/#v2:DYLgbgRgNALiBOBXAdlAJiA1AHwJIFsAHAe3hgGcACAZQE9yYBTfAWACgBZYtRYRygArxiAc3gBDVm0oyaiCJQ7iAlsgAUASnaydlAMLFk5YnwB0AdXjKmAGVWM1AIkeUAZJQBi44OUZbpsgCiyGhyEOzBoVw8fEA===), should get into branches by tomorrow.

**Comment by svick** [comment]
@ashmind Thanks.
