### ISSUE TITLE
InvalidOperationException at HandlePointerArithmetic

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#206]
```
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void C::M()
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.HandlePointerArithmetic(ILNode method) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 687
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 129
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 96
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 71
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 75
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 768
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 762
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 369
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddType(TypeDefinition typeDef) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 255
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddAssembly(ModuleDefinition moduleDefinition, Boolean onlyAssemblyLevel) in D:\$TC\work\c99972096bc51e45\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 208
   at SharpLab.Server.Decompilation.AstBasedDecompiler.Decompile(Stream assemblyStream, TextWriter codeWriter)
   at SharpLab.Server.MirrorSharp.SlowUpdate.WriteResult(IFastJsonWriter writer, Object result, IWorkSession session)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<SendSlowUpdateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

(Note to self: see secret gist for the example)

**Comment by ashmind** [comment]
Resolved by #238.
