### ISSUE TITLE
System.NotImplementedException: GenericInst

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#213]
See:
https://sharplab.io/#v2:D4bQKgpgzgLgFAEQDwHsBGArCBjGA+AOgFECAxASgF0BYAKAAEBmAAnoCZnJYBBGGAJwCWaAK4wIzAFysAjAV4DhYiHQDedAJBNO0GAqGjxcdFlzMT5Os2vN1tG8wC+dZ7Trb6MgGysOyMHhqmtoQAHYiALbMRFY2dg4apLHWro5AA==

```
System.NotImplementedException: GenericInst
   at Mono.Cecil.SignatureReader.ReadPrimitiveValue(ElementType type) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\AssemblyReader.cs:line 3079
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue(TypeReference type) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\AssemblyReader.cs:line 3047
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\AssemblyReader.cs:line 3027
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\AssemblyReader.cs:line 3027
   at Mono.Cecil.SignatureReader.ReadCustomAttributeFixedArgument(TypeReference type) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\AssemblyReader.cs:line 2959
   at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\AssemblyReader.cs:line 2953
   at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\AssemblyReader.cs:line 2456
   at Mono.Cecil.CustomAttribute.<Resolve>b__34_0(CustomAttribute attribute, MetadataReader reader) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\CustomAttribute.cs:line 186
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\ModuleDefinition.cs:line 880
   at Mono.Cecil.CustomAttribute.Resolve() in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\CustomAttribute.cs:line 184
   at ICSharpCode.Decompiler.Ast.AstBuilder.ConvertCustomAttributes(AstNode attributedNode, ICustomAttributeProvider customAttributeProvider, String attributeTarget) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1413
   at ICSharpCode.Decompiler.Ast.AstBuilder.ConvertAttributes(EntityDeclaration attributedNode, TypeDefinition typeDefinition) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1134
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 296
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddType(TypeDefinition typeDef) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 255
   at ICSharpCode.Decompiler.Ast.AstBuilder.AddAssembly(ModuleDefinition moduleDefinition, Boolean onlyAssemblyLevel) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 208
   at SharpLab.Server.Decompilation.AstBasedDecompiler.Decompile(Stream assemblyStream, TextWriter codeWriter)
   at SharpLab.Server.MirrorSharp.SlowUpdate.WriteResult(IFastJsonWriter writer, Object result, IWorkSession session)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<SendSlowUpdateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

**Comment by ashmind** [comment]
Does not happen anymore, probably fixed in the latest ILSpy.
