### ISSUE TITLE
Can't Run code which contains readonly struct

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#217]
Consider [trivial code that contains `readonly struct`](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMABAMICwAUAN4WG2G4CMAbPQCz0MAcAFAJSGUAvhWHkKCOBAAmAe0wAbAJ6FYGAMYxCAZQGigA):

```c#
class C
{
    static void Main() {}
}

readonly struct S {}
```

When I compile this code using compiler from `master` and try to Run it, I get:

```
Unbreakable.AssemblyGuardException: Custom types cannot be defined in system namespace System.Runtime.CompilerServices.
 at Unbreakable.Internal.AssemblyValidator.ValidateDefinition(TypeDefinition type)
 at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
 at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
 at SharpLab.Server.Execution.Executor.Execute(Stream assemblyStream, Stream symbolStream, IWorkSession session)
 at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__6.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

Decompiling the code indeed shows that it contains the compiler-generated type `IsReadOnlyAttribute` in the `System.Runtime.CompilerServices` namespace:

```c#
using Microsoft.CodeAnalysis;
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
[module: UnverifiableCode]
namespace Microsoft.CodeAnalysis
{
    [Embedded, CompilerGenerated]
    internal sealed class EmbeddedAttribute : Attribute
    {
    }
}
namespace System.Runtime.CompilerServices
{
    [Embedded, CompilerGenerated]
    internal sealed class IsReadOnlyAttribute : Attribute
    {
    }
}
internal class C
{
    private static void Main()
    {
    }
}
[IsReadOnly]
[StructLayout(LayoutKind.Sequential, Size = 1)]
internal struct S
{
}
```

**Comment by OmarTawfik** [comment]
+1 for this.
This is true for most C# 7.2 features, like `in` parameters or `ref readonly` return types.

**Comment by ashmind** [comment]
Thanks for reporting! I'm not actively working on the SharpLab backlog at the moment, but I'll try to find time for this one in the near future.
