### ISSUE TITLE
Allow System.Security.Cryptography

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#218]
I was trying to solve [a question on Reverse Engineering Stack Exchange](https://reverseengineering.stackexchange.com/q/16996/3615) by running [this code](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoRLUB0AygKYDGEYAlsAJ4EDCYtADsAPYDmYAhiwBa0suZGgIAVEgA9gwnHADM+AGwoATPgDsSAN44kBlErSq4AFnwAOABQBKXfsMBfRwdcqkAI3bsANkgAzaDIAfQRUVBtPWmASAG0AXSQANx4wM1t3PWxDXKQASCIACQBBVBS05ABeJCgSAHckYrKAWR4oHk4SABM7YTyBrxj4pNSwcpqxhEZ2AFsWCFiingBnfmsAUSgydm6qKE4CAFVxADFLAgBxEmAAIWGV6wAidn5gCDJ+AEcebuBObrQfhUJ62Wz9Qa5IotEoMZrlMYaGp1RrQ2Hw6xjVDg9yQ6KxRIVMBKSZpNQzeaLEjLNaYtJmAA0SAQTNQCBxOUhhjg2jGCjiCCSVVJ6TibKSADIJUT+aghSKzGK5cJ8i5sE4gA=):

```c#
using System;
using System.Security.Cryptography;
using System.Text;

public static class Program {
    public static void Main() {
    }
    
    static bool func_0118(byte[] var4)
    {
            SHA1 var0 = new SHA1Managed();
            byte[] var1 = var0.ComputeHash(Encoding.UTF8.GetBytes("ohtuchqadtgdunhi"));
            HMACSHA1 var2 = new HMACSHA1(var1);
            byte[] var3 = var2.ComputeHash(var4, 0, 10);
            return var3[0] == var4[10] && var3[1] == var4[11];
    }
}
```

The exception I got was:

```
Unbreakable.AssemblyGuardException: Namespace System.Security.Cryptography is not allowed.
 at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
 at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
 at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
 at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
 at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
 at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
 at SharpLab.Server.Execution.Executor.Execute(Stream assemblyStream, Stream symbolStream, IWorkSession session)
 at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__6.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

I think that types from the `System.Security.Cryptography` namespace should be safe, so executing them should be allowed (though I didn't go though all of them to verify this).

**Comment by ashmind** [comment]
Done, but in a limited way -- allowed specific APIs you used (seem safe) to limit the review scope.
Please raise a separate issue (or a PR) if any new APIs are needed.
