### ISSUE TITLE
Can't decompile code that uses Microsoft.VisualBasic

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#243]
When you try to decompile VB.NET code that uses Microsoft.VisualBasic to C# or VB.NET, an exception is thrown from `SharpLab.Server.Common.PreCachedAssemblyResolver.Resolve`.

For example, consider [this code](https://sharplab.io/#v2:DYLgbgRgNALuEB8DCwCGBndACJBYAUFkVgCICWAtljAPYyrDACeAggMowBOZAdgOYASLAF4sARgIBRHgBMcaTEA=) (which uses `Microsoft.VisualBasic.CompilerServices.Conversions.ToString`):

```vb
Class C
    Dim totallyAString$ = 1
End Class
```

When you try to decompile it to C# or VB.NET, it throws:

```
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void C::.ctor()
 ---> System.Exception: Assembly Microsoft.VisualBasic was not found in cache.
 at SharpLab.Server.Common.PreCachedAssemblyResolver.Resolve(AssemblyNameReference name)
 at Mono.Cecil.MetadataResolver.Resolve(TypeReference type) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\MetadataResolver.cs:line 105
 at Mono.Cecil.MetadataResolver.Resolve(MethodReference method) in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\MetadataResolver.cs:line 216
 at Mono.Cecil.MethodReference.Resolve() in D:\home\site\repository\source\#external\ILSpy\cecil\Mono.Cecil\MethodReference.cs:line 168
 at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.IntroducePropertyAccessInstructions(ILExpression expr, ILExpression parentExpr, Int32 posInParent) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 428
 at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.IntroducePropertyAccessInstructions(ILNode node) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 387
 at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.IntroducePropertyAccessInstructions(ILNode node) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 391
 at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 117
 at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 96
 at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 71
 --- End of inner exception stack trace ---
 at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 75
 at ICSharpCode.Decompiler.Ast.AstBuilder.CreateConstructor(MethodDefinition methodDef) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 870
 at ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 760
 at ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 369
 at ICSharpCode.Decompiler.Ast.AstBuilder.AddType(TypeDefinition typeDef) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 255
 at ICSharpCode.Decompiler.Ast.AstBuilder.AddAssembly(ModuleDefinition moduleDefinition, Boolean onlyAssemblyLevel) in D:\home\site\repository\source\#external\ILSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 208
 at SharpLab.Server.Decompilation.AstBasedDecompiler.Decompile(Stream assemblyStream, TextWriter codeWriter)
 at SharpLab.Server.MirrorSharp.SlowUpdate.WriteResult(IFastJsonWriter writer, Object result, IWorkSession session)
 at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<SendSlowUpdateAsync>d__5.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

[Disassembling to IL works fine.](https://sharplab.io/#v2:DYLgbgRgNALiCWwA+BhYBDAzpgBCgsAFA4k4Ai8AtjjAPYzrDACeAggMowBO8AdgOYASHAF4cARiIBRXgBM8GbEA)

This is probably a duplicate of https://github.com/ashmind/SharpLab/issues/198, but that was closed as "cannot reproduce".

**Comment by ashmind** [comment]
Thanks, yes it the same. Still can't reproduce on local, but I'll do some research.

**Comment by ashmind** [comment]
@svick Rewritten the whole thing, hope it should work now.
Note that's only for Default, other branches will update in few hours if build works well.
