### ISSUE TITLE
Allow using the new() constraint in Run mode

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#245]
When I try to Run code that uses the generic constraint `new()`, I get the exception "AssemblyGuardException: Type System.Activator is not allowed."

For example, consider [this code](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgARwIwHYCwAoA3jpQlVANhQBZiAOACgEolckBfAotwgFSQGEwBTAIbB+ASSgBnYIKgBjfgB5OAPnpIA7gAt+ApNxBIo/dWoC8yw8b30A3DmZA):

```c#
class Program
{
    static void Main() { }
    
    T CreateInstance<T>() where T : new() => new T();
}
```

When I try to Run it, I get:

```
Unbreakable.AssemblyGuardException: Type System.Activator is not allowed.
 at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
 at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
 at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
 at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
 at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
 at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
 at SharpLab.Server.Execution.Executor.Execute(Stream assemblyStream, Stream symbolStream, IWorkSession session)
 at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__6.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

This is because the code actually [compiles to](https://sharplab.io/#v2:D4AQTABCCMDsCwAoA3ki6rQGxQCyYA4AKASgmQgF80Mb0AVCAYQCcBTAQwBc2BJAOwDOXDvwDGbADz0AfKQgB3ABZt2ERgC4I/NgvkBeGdt3rSAbiSUgA===):

```c#
private T CreateInstance<T>() where T : new()
{
    return Activator.CreateInstance<T>();
}
```

I understand that `Activator.CreateInstance` is potentially a dangerous method, so it might not be possible to solve this. But I thought that creating this issue still makes sense, in case it's a solvable problem.

**Comment by ashmind** [comment]
Thanks! I might be able to allow it -- I'll look into it.

**Comment by ashmind** [comment]
I've looked into it, and it's possible, but requires quite a bit of new features in Unbreakable.
It's not a problem, but given Run is not my first priority I will deprioritize this one for now.

**Comment by ashmind** [comment]
Hi @svick, this has been resolved now that SharpLab has moved to a new Run mode that no longer blocks individual types.
