### ISSUE TITLE
async Main doesn't work in Run mode

### ISSUE THREAD

**Issue by ForNeVeR** [ashmind/SharpLab#247]
I've tried to compile the following code:

```csharp
using System;
using System.Threading.Tasks;
public static class Program {
    public static async Task Main() {
        Console.WriteLine("🌄");
    }
}
```

The compilation failed with an error:

```
Unbreakable.AssemblyGuardException: Type System.Runtime.CompilerServices.AsyncTaskMethodBuilder is not allowed.
   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
   at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(Stream assemblyStream, Stream symbolStream, IWorkSession session)
   at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

**Comment by ashmind** [comment]
This should work for other modes, but not `Run` at the moment.
`Run` does not currently allow any kind of asynchronous operations, including `async Main`.

**Comment by ashmind** [comment]
ashmind/Unbreakable#1 tracks this as well, but I don't have any timeline planned at the moment.

**Comment by ForNeVeR** [comment]
Oh, sorry, that's right. It's not an issue for me then. Thanks, I'll update the title.

**Comment by ashmind** [comment]
Hi @ForNeVeR, this is now resolved, as new Run mode does not have restrictions on async code.

**Comment by ForNeVeR** [comment]
https://github.com/ashmind/Unbreakable/issues/1 is still open though. Is it okay?

**Comment by ashmind** [comment]
Yep, current Run mode does not use Unbreakable.
