### ISSUE TITLE
Type System.MemoryExtensions is not allowed

### ISSUE THREAD

**Issue by davidwengier** [ashmind/SharpLab#295]
Was hoping to try out the new Inspect features and compare Span<T> to non-span but unfortunately as soon as I do something like "blah".AsSpan() it won't run as Unbreakable spots it.

`
Unbreakable.AssemblyGuardException: Type System.MemoryExtensions is not allowed.
   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
   at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(Stream assemblyStream, Stream symbolStream, IWorkSession session)
   at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__7.MoveNext()
`

Is that intentional? Or am I doing something wrong?

**Comment by ashmind** [comment]
Hmm, even when I allow it you can't inspect spans yet, as they can't be converted to objects for `Inspect.Heap` and can't be used generically for `Inspect.Stack`. I'll probably need a separate `Inspect.Span` for those.

**Comment by ashmind** [comment]
Added Inspect.Span ticket at #297.

**Comment by davidwengier** [comment]
Thanks!
