### ISSUE TITLE
NullReferenceException for null in Syntax Tree mode

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#311]
It seems that when I attempt to view the Syntax Tree of code that contains the `null` literal, a `NullReferenceException` is throw.

Specifically, [this code](https://sharplab.io/#v2:C4LghgzsA+ACBMACAwgWAFAG8ON42ALIgLIAUAlDntunnYgPYBGAVgKYDGwiAHogLyIAdgFcANmIDcVXAF8MsoA=):

```c#
class C
{
    void M()
    {
        object x = null;
    }
}
```

throws:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , IOperation , IFastJsonWriter )
   at SharpLab.Server.Decompilation.Internal.RoslynOperationPropertySerializer.SerializeProperties(IOperation operation, IFastJsonWriter writer)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeOperation(IOperation operation, IFastJsonWriter writer)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeNode(SyntaxNode node, SemanticModel semanticModel, IFastJsonWriter writer, String specialParentPropertyName)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeAst(RoslynAst ast, IFastJsonWriter writer, IWorkSession session)
   at SharpLab.Server.Decompilation.AstOnly.RoslynAstTarget.SerializeAst(Object ast, IFastJsonWriter writer, IWorkSession session)
   at SharpLab.Server.MirrorSharp.SlowUpdate.WriteResult(IFastJsonWriter writer, Object result, IWorkSession session)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<SendSlowUpdateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

**Comment by ashmind** [comment]
This will take 5-10 mins to deploy to the Default branch, and sometime before tomorrow for other branches.
