### ISSUE TITLE
No way to run a program which declares an event

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#334]
[Example](https://sharplab.io/#v2:EYLgHgbALANANiAbsGAXEAnArgOwD4CSAtgA4D2GqAzgAQDKAnlagKZECwAUFwApbBwAlgGMaAWTIATLHBbiAhoJxcaqmnwEj6/BUoAUAShVqTx1QFEck7cC6XrE6bK69+Q0QGE48qrQ9n1Ny1zRBYcVBoAFRZmGgBBWhCw1AAJeStZDDsrGi8fKi4gA):

```vb.net
Imports System

Public Module Main
    Public Sub Main()
        
    End Sub
End Module

Public Class C
    Public Event Test As EventHandler
End Class
```

```
Unbreakable.AssemblyGuardException: Namespace System.Threading is not allowed.
   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session)
   at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

Also, the stack trace is really hard to copy. It ends up on a single line when you copy in Firefox and has an extra indent and double spacing if the selection snaps to include more of the page.

**Comment by svick** [comment]
This is not specific to VB, [the following C# code also fails with the same exception](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoHcBMKqA7DgN45JVEBsKALEQBwAUAlEmUgL6XV9UApgDdBUYEgCio8QAkAhlAAmAG0FgpWbNyA):

```c#
using System;

class Program
{
    static void Main() { }
    
    event EventHandler E;
}
```

(Which makes sense, since both languages seem to generate the same IL for the event accessors.)

**Comment by jnm2** [comment]
@svick Thank you, funny I hadn't tried that. It would be a good thing if only explicit using declarations triggered Unbreakable, right?

**Comment by ashmind** [comment]
That's interesting, thanks for reporting! I might just allow `Interlocked`, can't think of a scenario where it could do much damage. No timeline yet though.

**Comment by ashmind** [comment]
This should be fine now.
