### ISSUE TITLE
Allow FormattableString

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#339]
In C#, interpolated string literals can be converted to `string`, but also to `FormattableString` or `IFormattable` by using `FormattableStringFactory`. But when I try to run such code in SharpLab, I can't.

For example, [this code](https://sharplab.io/#v2:C4LgTgrgdgPhDOBLKBzABAZQJ72AUwFsBuAWAChyBjAGwEN540Bhcgb3LU7V1uEUrQA3APaIAJmgCytZAAoAlBy7syXNWgBiwsAV7BaAI2p4MwMMnQAzRgF40AEgBEj0qq4Bfcu6A===):

```c#
using System;

class C
{
    static void Main()
    {
        FormattableString fs = $"";
    }
}
```

Produces:

```
Unbreakable.AssemblyGuardException: Type System.Runtime.CompilerServices.FormattableStringFactory is not allowed.
   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
   at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session)
   at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

**Comment by ashmind** [comment]
Thanks for reporting! Yep, this should be allowed.

**Comment by ashmind** [comment]
Resolved in Default, should be available in branches in a day or two.
