### ISSUE TITLE
Simple safe operation on ref parameter not allowed in Run mode

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#345]
Consider [this code](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgARwIwHYCwAoA3jpQlVANhQBYkBZAQwEsoAKASiVyQF8cCi5KrGYAKYAzJA2DjWAXgB84gNQKA3Dg5A==):

```c#
class Program
{
    static void Main() { }

    void M(ref int i) => i++;
}
```

Trying to execute it in Run mode results in:

```
Unbreakable.AssemblyGuardException: Method System.Void Program::M(System.Int32&) performs pointer operations which cannot be validated.
   at Unbreakable.Internal.AssemblyValidation.PointerOperationValidator.ValidateInstruction(Instruction instruction, MethodDefinition method)
   at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session)
   at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

But the operation performed in the code (incrementing an integer passed by reference) is safe, so it would be nice if it was allowed.

**Comment by ashmind** [comment]
Thanks -- I'll take a look when I have time (might be a few months, not actively working on SharpLab at the moment).

**Comment by ashmind** [comment]
Resolved (in Default, other branches might take a day or so).
