### ISSUE TITLE
ArgumentNullException in MirrorSharp.SlowUpdate

### ISSUE THREAD

**Issue by danmosemsft** [ashmind/SharpLab#360]
I ran [this](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgBgATIIwG4CwAUIQHYCGAtgKYDOADqQMaXoBiA9m4QN6Hp+YAmTFgDsvfjwL9pwgGzowxYOgCypRQApsqANoBddKQBOAc2oBKcTPSSAkPcXKw6ALzpU+KdZkB3ABaQzBrARgCulJZe3hJW0ei2YPDwnnH8CQBm6BrOAHzoWKio5ugARkaUpADWKanoAL6x0QDCbMTUbBCUAHQA6kZgwJTZ5jWp6WxGWTg4kbU2jd4JSaNxGVm56AKFxWUV1QvWDVFxyCIKK9JHl4RHQA==) and after a long pause got this:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

Thanks for a great tool.

**Comment by ashmind** [comment]
Thanks for reporting! I'm not currently actively working on SharpLab, so the fix might take a bit of time.
But I'll definitely look into it.

**Comment by danmosemsft** [comment]
No problem on my side..just thought I'd log it.

**Comment by Suchiman** [comment]
Also sometimes happens when you open sharplab.io fresh or when you click on someones hyperlink to a sample. Typically goes away with F5 but appears to be some kind of corrupted state because once you've seen this, you're likely to run into it again.
