### ISSUE TITLE
AssemblyGuardException when post-incrementing tuple member

### ISSUE THREAD

**Issue by canton7** [ashmind/SharpLab#378]
The code

```csharp
public static class Program {
    public static void Main() {
        var x = (3, 4);
        x.Item1++;
    }
}
```

Produces the error:

```
Unbreakable.AssemblyGuardException: Method System.Void Program::Main() performs pointer operations which cannot be validated.
 at Unbreakable.Internal.AssemblyValidation.PointerOperationValidator.ValidateInstruction(Instruction instruction, MethodDefinition method)
 at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
 at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
 at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
 at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
 at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session)
 at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__7.MoveNext() 
...
```

[Link](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIGYAEqCMA2bAJmxwHZMBvAWAChN7stcDUAWTAWQEMBLKACgCUlWgzGYAblzCYAHpgC8mfuhiZWggNyjx9WQDoAksACmAWxyJE2ugwC+tO0A=).

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look (might take some time).

**Comment by ashmind** [comment]
Hi @canton7, this has been resolved (by moving to a new execution model).

**Comment by canton7** [comment]
Thanks!
