### ISSUE TITLE
System.NullReferenceException in Flow.ReportValue when ToString returns null

### ISSUE THREAD

**Issue by canton7** [ashmind/SharpLab#380]
[Repro](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABABgAJiBGAbgFgAoYgZkqoDZKAmNgdnIDejciMqtqnYgBZyAWQgBLTAAoAlIOGit1AJzKAGssxwA7uQDCa1avoMtAX00inYtpKoVDAe2AArOADGMORe6gC8AHzkAETR5Pghto4MjCzcFoxCdqJpXgBuiAgKOHBsFAAqXgDKMEWYAOZq5JHkmOgANu00ooz2QA=)

```csharp
using System;
public static class Program {
    public static void Main() {
        Console.WriteLine(X(new C()));
    }

    public static string X(object o) => "" + o;
}

public class C
{
    public override string ToString() => null;   
}
```

Produces the exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpLab.Runtime.Internal.ObjectAppender.AppendString(StringBuilder builder, String value, Nullable`1 maxLength)
   at SharpLab.Runtime.Internal.ObjectAppender.Append[T](StringBuilder builder, T value, Nullable`1 maxEnumerableItemCount, Nullable`1 maxValueLength)
   at SharpLab.Runtime.Internal.Flow.ReportValue[T](T value, String name, Int32 lineNumber)
   at Program.X(Object o) at Program.Main()
```

**Comment by ashmind** [comment]
Thanks for reporting!

**Comment by ashmind** [comment]
Resolved in Default, might take a bit of time to apply to other branches.
