### ISSUE TITLE
IndexOutOfRangeException at TryInsertReportMethodArguments

### ISSUE THREAD

**Issue by Suchiman** [ashmind/SharpLab#411]
```csharp
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        List<int> digits = new List<int>();
        digits.Sort((a, b) =>
        {
            return a.CompareTo(b);
        });
    }
}
```

[sharplab](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwBYDcBYAUHuAJhVQHY8BvPJGkgNhXSQFkBDASygAo0EBtALpJWYAOYBnAJTVaVXLQVIAMu3HAAPJ2AA+JABN2o9sHFIAvEigBTAO7LVGrdq6Sc8xTQNGTAOgDKAPZgwFxcrAA0SABGkubaMh5yHh5wpMI+AMIBALYADiJWACoBXDFuyUgAvq4JVXiVQA)

output
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.TryInsertReportMethodArguments(ILProcessor il, Instruction instruction, MethodDefinition method, ReportMethods flow, IWorkSession session, Int32& index)
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(MethodDefinition method, ReportMethods flow, IWorkSession session)
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(TypeDefinition type, ReportMethods flow, IWorkSession session)
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(TypeDefinition type, ReportMethods flow, IWorkSession session)
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(AssemblyDefinition assembly, IWorkSession session)
   at SharpLab.Server.AspNetCore.Execution.ExecutorBase.Execute(CompilationStreamPair streams, IWorkSession session)
   at SharpLab.Server.MirrorSharp.SlowUpdate.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessInternalAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MirrorSharp.Internal.Connection.<ReceiveAndProcessAsync>d__12.MoveNext()
```

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look.

**Comment by ashmind** [comment]
@jsk95 This might be a good first issue -- hopefully should be clear if you start with a unit-test.

**Comment by jsk95** [comment]
Will take a look

**Comment by ashmind** [comment]
Resolved by @AbeniMatteo. Pls give it a few minutes to deploy to Default site, and then up to a day to deploy to all branches.
