### ISSUE TITLE
IComparable/IEquatable is not allowed

### ISSUE THREAD

**Issue by udaken** [ashmind/SharpLab#454]
I tryed this code:
```cs
using System;

class Program
{
    static void Main()
    {
        ((IComparable<int>)0).CompareTo(1);
        ((IEquatable<int>)0).Equals(1);
    }
}
```
the exception I got was:
```
Unbreakable.AssemblyGuardException: Type System.IEquatable`1 is not allowed.

   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)

   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)

   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)

   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)

   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)

   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)

   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Executor.cs:line 72

   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in C:\projects\sharplab\source\Server\MirrorSharp\SlowUpdate.cs:line 103

   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)

   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)

   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

I think these interfaces are safe.

**Comment by ashmind** [comment]
Thanks! I agree -- I'll take a look when I have time.

**Comment by ashmind** [comment]
Resolved (all work done by @teo-tsirpanis) -- deployed now, though only to Default and various architectures. "Roslyn branches" are not deploying properly for unrelated reasons.
