### ISSUE TITLE
FlowReportingRewriter causes Mono.Cecil to throw ArgumentException: "opcode"

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#456]
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmAZgFgAoAb2oAJH7SSGm6qmv6AxCCABQBGNPRKiyo9PQCsASgDcbRgF9l9dQAcoASwBuAQwwxmQpMxS9+AnXgz0Do2/eBO79MG/sATL/Rhy6hxcalShQA===

```cs
public static class Program
{
    public static void Main()
    {
        Foo(1, 2, 3, 4, 5);
    }
    
    private static void Foo(int a, int b, int c, int d, int e)
    {
    }
}
```

```
System.ArgumentException: opcode
   at Mono.Cecil.Cil.Instruction.Create(OpCode opcode, SByte value)
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.TryInsertReportMethodArguments(ILProcessor il, Instruction instruction, SequencePoint sequencePoint, MethodDefinition method, ReportMethods flow, IWorkSession session, Int32& index) in C:\projects\sharplab\source\Server\Execution\Internal\FlowReportingRewriter.cs:line 156
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(MethodDefinition method, ReportMethods flow, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Internal\FlowReportingRewriter.cs:line 111
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(TypeDefinition type, ReportMethods flow, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Internal\FlowReportingRewriter.cs:line 87
   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(AssemblyDefinition assembly, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Internal\FlowReportingRewriter.cs:line 57
   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Executor.cs:line 62
   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in C:\projects\sharplab\source\Server\MirrorSharp\SlowUpdate.cs:line 103
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

**Comment by ashmind** [comment]
Very interesting, thanks for reporting! Keen to take a look, though no specific timeline.

**Comment by SirJosh3917** [comment]
I have also ran into this bug - it triggers as soon as there are 4 constructor parameters in my case. Ran using the experimental `Run` mode in Release.

```cs
public struct FourParameterCtor
{
    public static void Main()
    {
    }
    
    public FourParameterCtor(int p1, int p2, int p3, int p4)
    {
    }
}
```

```
System.ArgumentException: opcode

   at Mono.Cecil.Cil.Instruction.Create(OpCode opcode, SByte value)

   at SharpLab.Server.Execution.Internal.CecilExtensions.CreateLdargBest(ILProcessor il, ParameterReference parameter) in C:\projects\sharplab\source\Server\Execution\Internal\CecilExtensions.cs:line 22

   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.TryInsertReportMethodArguments(ILProcessor il, Instruction instruction, SequencePoint sequencePoint, MethodDefinition method, ReportMethods flow, IWorkSession session, Int32& index) in C:\projects\sharplab\source\Server\Execution\Internal\FlowReportingRewriter.cs:line 156

   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(MethodDefinition method, ReportMethods flow, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Internal\FlowReportingRewriter.cs:line 111

   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(TypeDefinition type, ReportMethods flow, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Internal\FlowReportingRewriter.cs:line 87

   at SharpLab.Server.Execution.Internal.FlowReportingRewriter.Rewrite(AssemblyDefinition assembly, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Internal\FlowReportingRewriter.cs:line 57

   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Executor.cs:line 63

   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in C:\projects\sharplab\source\Server\MirrorSharp\SlowUpdate.cs:line 103

   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)

   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)

   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

https://sharplab.io/#v2:C4LgTgrgdgPgAgZgAQGdiQMbCQMQPYRgAKAhmCQLYCmwVYAwsHmALABQA3u0j0nAEz9uvLm15IAvsJ7S+yfIVLlqtBkzAAKAJZRsABwCMAGiQ79/E2aR6El3dYAsASlmjxUthKA=

**Comment by jnm2** [comment]
Makes sense because you have an implicit `this` argument in addition to the four constructor arguments.

**Comment by ashmind** [comment]
Fixed/deployed.
