### ISSUE TITLE
Help with first steps

### ISSUE THREAD

**Issue by m7nu3l** [ashmind/SharpLab#538]
Hi.

Sharplab has been really useful to me and I'd like to extend its functionality. Although, I'm having some issues getting started with local development. 

I read the instructions and executed `sl setup`. It successfully builds everything. However, when I run Server and try to locally connect, I get 404 on my browser.

1. `sl setup` outputs `Server -> D:\dev\sharplab-vanilla\source\Server\bin\Debug\netcoreapp3.1\publish\`
2. From my cmd I do `D:\dev\sharplab-vanilla\source\Server\bin\Debug\netcoreapp3.1\SharpLab.Server.exe` which outputs:

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\dev\sharplab-vanilla
```
3. I connect from my browser to: http://localhost:5000, https://localhost:5001 and http://localhost:49891/. Everytime I try, I get 404. The first URL outputs in the Server.exe console:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 24.7209ms 404
```

Alternatively, I also run Server with IIS Express from Visual Studio (green play button). The browser pops up and I get 404. 

I'm pretty sure I must be forgetting something stupid. The truth is that it is my very first time regarding C# web development.

------

I work on a three address code representation of CIL bytecode. I'd really like to integrate it into your website!

Best,
Manuel.

**Comment by ashmind** [comment]
Thanks for the detailed report!
Yep, setup is a bit broken at the moment, I'm looking to improve it.

I think one of the main problems is that you are running Server, but without WebApp it will have no UI.

I recommend installing https://github.com/dotnet/tye and running `dotnet tye run` in the main folder.
If that is successful, you should have both frontend and backend built and running.

I am going to look into improving setup as part of #488, however can't promise any specific timeline.

**Comment by ashmind** [comment]
I just fixed `sl setup` which will install correct version of `tye` for you.

**Comment by m7nu3l** [comment]
Awesome! \0/ 

As soon as I can, I'll try to test it and tell you if it is working.

**Comment by m7nu3l** [comment]
@ashmind I had the chance to test your latest commit. I deleted the old repo and cloned it again.

I ran `sl setup` and it built. Then, I executed `dotnet tye run` yielding the following error.

```
D:\dev\sharplab-vanilla>dotnet tye run
Loading Application Details...
Launching Tye Host...

[22:53:00 INF] Executing application from D:\dev\sharplab-vanilla\tye.yaml
[22:53:01 INF] Dashboard running on http://127.0.0.1:8000
[22:53:01 INF] Building projects
[22:53:07 INF] Launching service webapp-assets_f16509fa-e: pwsh -Command "npm run watch"
[22:53:07 INF] Launching service webapp-dotnet_7651076c-b: D:\dev\sharplab-vanilla\source\WebApp\bin\Debug\netcoreapp3.1\SharpLab.WebApp.exe
[22:53:07 ERR] Failed to launch process for service webapp-assets_f16509fa-e
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 106
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 267
```

In case you need more information, please tell me. I didn't find any log error.

Thanks for your support!

**Comment by m7nu3l** [comment]
Here goes more info. 

I can access the Tye Dashboard (http://localhost:8000/). There are two services listed:

![image](https://user-images.githubusercontent.com/3461126/88004358-3d1b3d80-cadd-11ea-84c3-d988bff9261f.png)


webapp-assets's log is:

```
[webapp-assets_35adf907-b]:pwsh -Command "npm run watch"
[webapp-assets_875b0e8e-3]:pwsh -Command "npm run watch"
[webapp-assets_7200745b-5]:pwsh -Command "npm run watch"
[webapp-assets_986c37e2-3]:pwsh -Command "npm run watch"
```

webapp-dotnet's log is:

```
[]([webapp-dotnet_422ae9ec-6]:D:\dev\sharplab-vanilla\source\WebApp\bin\Debug\netcoreapp3.1\SharpLab.WebApp.exe
[webapp-dotnet_422ae9ec-6]: info: Microsoft.Hosting.Lifetime[0]
[webapp-dotnet_422ae9ec-6]: Now listening on: http://localhost:54100
[webapp-dotnet_422ae9ec-6]: info: Microsoft.Hosting.Lifetime[0]
[webapp-dotnet_422ae9ec-6]: Application started. Press Ctrl+C to shut down.
[webapp-dotnet_422ae9ec-6]: info: Microsoft.Hosting.Lifetime[0]
[webapp-dotnet_422ae9ec-6]: Hosting environment: Development
[webapp-dotnet_422ae9ec-6]: info: Microsoft.Hosting.Lifetime[0]
[webapp-dotnet_422ae9ec-6]: Content root path: D:\dev\sharplab-vanilla\source\WebApp
[webapp-dotnet_422ae9ec-6]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[webapp-dotnet_422ae9ec-6]: Request starting HTTP/1.1 GET http://localhost:54100/
[webapp-dotnet_422ae9ec-6]: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[webapp-dotnet_422ae9ec-6]: Request finished in 104.7038ms 404)
```

Accessing http://localhost:54100/ returns 404.

**Comment by ashmind** [comment]
Interesting. Do you have `pwsh` on PATH?

**Comment by m7nu3l** [comment]
Sorry for the long pause @ashmind 

After a Windows update my laptop was not working anymore. So I had to re install Windows on it. I lost the original working environment. However, I tried again from a fresh install.

I'm still not able to run it, although here are some issues I faced and how I solved them. All this happened while running sl setup and dotnet run tye from a cmd.

```
File C:\dev\SharpLab\#scripts\setup.ps1 cannot be loaded. The file C:\dev\SharpLab\#scripts\setup.ps1 is not digitally
signed. You cannot run this script on the current system. For more information about running scripts and setting
execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

I solved it by running a Powershell instance and executing: Set-ExecutionPolicy Unrestricted (I know this is not the best way to do it probably - security wise).

Then I had:

Installing node modules
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\dev\SharpLab\#scripts\setup.ps1:24 char:5
+     npm ci
+     ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

I solved it by installing NodeJS LTS from its official website. The strange thing is that when I installed VS I had choosen to install NodeJS stuff.

Lastly, I had an issue where I didn't have pwsh available on the cmd. I solved it by running dotnet tool install -g powershell. 

After `sl setup` executes I run` dotnet tye run` but the browser loads a blank page.
```

[12:45:07 INF] Executing application from C:\dev\SharpLab\tye.yaml
[12:45:07 INF] Dashboard running on http://127.0.0.1:8000
[12:45:07 INF] Building projects
[12:45:09 INF] Launching service webapp-assets_bf60f0d2-f: pwsh -Command "npm run watch"
[12:45:09 INF] Launching service webapp-dotnet_3255b876-a: C:\dev\SharpLab\source\WebApp\bin\Debug\netcoreapp3.1\SharpLab.WebApp.exe
[12:45:09 INF] webapp-assets_bf60f0d2-f running on process id 2896
[12:45:09 INF] No process was selected. Waiting.
[12:45:09 INF] webapp-dotnet_3255b876-a running on process id 12404 bound to http://localhost:54100
[12:45:09 INF] No process was selected. Waiting.
[12:45:10 INF] Selected process 2896.
[12:45:10 INF] Listening for event pipe events for webapp-assets_bf60f0d2-f on process id 2896
[12:45:10 INF] Selected process 12404.
[12:45:10 INF] Listening for event pipe events for webapp-dotnet_3255b876-a on process id 12404
[12:45:10 INF] Event pipe collection completed for webapp-assets_bf60f0d2-f on process id 2896
[12:45:11 INF] webapp-assets_bf60f0d2-f process exited with exit code 1
[12:45:11 INF] Launching service webapp-assets_b92f130b-6: pwsh -Command "npm run watch"
[12:45:11 INF] webapp-assets_b92f130b-6 running on process id 1548
[12:45:11 INF] No process was selected. Waiting.
[12:45:11 INF] Selected process 1548.
[12:45:11 INF] Listening for event pipe events for webapp-assets_b92f130b-6 on process id 1548
[12:45:11 INF] Event pipe collection completed for webapp-assets_b92f130b-6 on process id 1548
[12:45:12 INF] webapp-assets_b92f130b-6 process exited with exit code 1
[12:45:12 INF] Launching service webapp-assets_99bffc4c-6: pwsh -Command "npm run watch"
[12:45:12 INF] webapp-assets_99bffc4c-6 running on process id 7736
[12:45:12 INF] No process was selected. Waiting.
```

Similarly happens if I run it through Visual Studio.

**Comment by ashmind** [comment]
Thanks for the thorough approach! What do you see if you manually run `npm run build` under `source\WebApp\`?

**Comment by m7nu3l** [comment]
Thanks @ashmind 

Hmm... I think I have another missing dependency! Am I missing TypeScript or something like it? 

```
C:\dev\SharpLab\source\WebApp>npm run build

> sharplab@0.0.0 build C:\dev\SharpLab\source\WebApp
> ts-node-script ./build.ts

(node:3048) ExperimentalWarning: The ESM module loader is experimental.
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\dev\SharpLab\source\WebApp\build.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:244:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Loader.import (internal/modules/esm/loader.js:178:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharplab@0.0.0 build: `ts-node-script ./build.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharplab@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manuel\AppData\Roaming\npm-cache\_logs\2020-08-17T18_58_35_653Z-debug.log
```

**Comment by m7nu3l** [comment]
Here you have the log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle sharplab@0.0.0~prebuild: sharplab@0.0.0
6 info lifecycle sharplab@0.0.0~build: sharplab@0.0.0
7 verbose lifecycle sharplab@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle sharplab@0.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\dev\SharpLab\source\WebApp\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\Manuel\AppData\Local\Microsoft\WindowsApps;C:\Users\Manuel\.dotnet\tools;C:\Users\Manuel\AppData\Roaming\npm
9 verbose lifecycle sharplab@0.0.0~build: CWD: C:\dev\SharpLab\source\WebApp
10 silly lifecycle sharplab@0.0.0~build: Args: [ '/d /s /c', 'ts-node-script ./build.ts' ]
11 silly lifecycle sharplab@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle sharplab@0.0.0~build: Failed to exec build script
13 verbose stack Error: sharplab@0.0.0 build: `ts-node-script ./build.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid sharplab@0.0.0
15 verbose cwd C:\dev\SharpLab\source\WebApp
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error sharplab@0.0.0 build: `ts-node-script ./build.ts`
22 error Exit status 1
23 error Failed at the sharplab@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by ashmind** [comment]
Thanks! I can reproduce it in node `12.18.3` (but not in the older version of node I had before).
I'll investigate and get back to you (can't promise any specific time yet).

**Comment by m7nu3l** [comment]
No worries. Take your time.

**Comment by ashmind** [comment]
Please try branch [edge](https://github.com/ashmind/SharpLab/tree/edge), added a potential fix there (don't remember if it has any other implications, so not in main branch yet).

**Comment by m7nu3l** [comment]
I checked out branch edge.

Then, I tried sl setup and still I only get a blank page.

Lastly, I tried npm run build in WebApp and I got the same error as before.

```
C:\dev\SharpLab\source\WebApp>npm run build

> sharplab@0.0.0 build C:\dev\SharpLab\source\WebApp
> ts-node-script ./build.ts

(node:8228) ExperimentalWarning: The ESM module loader is experimental.
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\dev\SharpLab\source\WebApp\build.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:244:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Loader.import (internal/modules/esm/loader.js:178:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharplab@0.0.0 build: `ts-node-script ./build.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharplab@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manuel\AppData\Roaming\npm-cache\_logs\2020-08-17T21_13_32_723Z-debug.log
```

**Comment by m7nu3l** [comment]
Arghhh. Forget my last update, I did something wrong. On edge, npm run build works! \0/

```
C:\dev\SharpLab\source\WebApp>npm run build

> sharplab@0.0.0 build C:\dev\SharpLab\source\WebApp
> ts-node-script ./build.ts

task default starting...
task icons starting...
task manifest starting...
task less starting...
task ts starting...
task ts-lint starting...
task manifest completed [94ms]
task icons completed [99ms]
task less completed [466ms]
task ts-lint completed [9.914s]
task ts-main starting...

./ts/app.ts → ./wwwroot/app.min.js...
created ./wwwroot/app.min.js in 14.3s
task ts-main completed [15.4s]
task ts completed [24.920s]
task html starting...
task html completed [43ms]
task default completed [24.969s]
```

**Comment by m7nu3l** [comment]
If you run sl setup && dotnet tye run before manually executing npm build run, it still doesn't work. However, if you run npm build run and after you run sl setup && dotnet tye run you can browse to Sharplab locally \0/

**Comment by ashmind** [comment]
Glad to hear it works (even if the flow is awkward for now).
I'll investigate `sl setup && dotnet tye run` issue further (when I have some time).

**Comment by m7nu3l** [comment]
@ashmind How are you? I hope you are doing great.

I found some time to resume my work with Sharplab. I started again by running ` sl setup` (on a fresh repository) and I'm having the following error. This happens in main and edge branches.

Command: `sl setup`
```
Copy-Item : Cannot find path 'C:\Users\Manuel\Desktop\SharpLab\source\WebApp\.env.template' because it does not exist.
At C:\Users\Manuel\Desktop\SharpLab\#scripts\setup.ps1:12 char:5
+     Copy-Item './source/WebApp/.env.template' './source/WebApp/.env'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Manuel...p\.env.template:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

**Comment by m7nu3l** [comment]
@ashmind  I think I got it:

```
diff --git a/#scripts/setup.ps1 b/#scripts/setup.ps1
index ad37bc4..2e13826 100644
--- a/#scripts/setup.ps1
+++ b/#scripts/setup.ps1
@@ -8,8 +8,8 @@ if ($LastExitCode -ne 0) {
 }

 Write-Host "Creating stub .env" -ForegroundColor White
-if (!(Test-Path './source/WebApp/.env')) {
-    Copy-Item './source/WebApp/.env.template' './source/WebApp/.env'
+if (!(Test-Path './source/WebApp.Server/.env')) {^M
+    Copy-Item './source/WebApp.Server/.env.template' './source/WebApp.Server/.env'^M
 }
```

 Write-Host "Installing local tools" -ForegroundColor White
Based on changes done here: https://github.com/ashmind/SharpLab/commit/38e84123de983506348b96a44d4fe64a461b4a96

**Comment by ashmind** [comment]
Yep that's very unlucky timing, it was OK for a while, but I literally just broke it yesterday and was going to revisit it (need to make sure `dotnet tye run` actually works as well).

**Comment by kkokosa** [comment]
Hm.. any updates on this? Fresh repository gives the same error while `sl setup`. I could help but it seems pretty deep change made here...👀

**Comment by ashmind** [comment]
Sure -- applied a fix, please give it a try.

**Comment by kkokosa** [comment]
Yes, it helped @ashmind, thank you! Issue may be closed.

**Comment by joelpryde** [comment]
I seem to still be getting this on main branch:
```
10:31:59 ERR] Failed to launch process for service webapp-assets_c2027d2c-6
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 113
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
```

pwsh is in my path and I have run `sl setup` and `npm run build` successfully.

**Comment by kkokosa** [comment]
Are you able to execute: `pwsh -Command "npm run start"` in `source/WebApp`? Beacause this is what Tye is trying to execute here

**Comment by joelpryde** [comment]
I am not unfortunately:

```
C:\Users\joelp\Documents\repos\SharpLab\source\WebApp>pwsh -Command "npm run start"

> sharplab@0.0.0 start
> ts-node-script ./scripts.ts start --watch

task start starting...
task build starting...
task less starting...
task ts starting...
task asm starting...
task icons starting...
task manifest starting...
task html starting...
task latest starting...
task asm failed:
TypeError: Cannot read property 'split' of undefined
    at oldowan_1.task.watch (C:\Users\joelp\Documents\repos\SharpLab\source\WebApp\scripts.ts:80:10)
    at task.run (C:\Users\joelp\Documents\repos\SharpLab\source\WebApp\node_modules\oldowan\dist\index.js:74:13)
    at C:\Users\joelp\Documents\repos\SharpLab\source\WebApp\scripts.ts:90:5
    at task.run (C:\Users\joelp\Documents\repos\SharpLab\source\WebApp\node_modules\oldowan\dist\index.js:74:13)
    at async Promise.all (index 1)
    at C:\Users\joelp\Documents\repos\SharpLab\source\WebApp\scripts.ts:149:5
    at task.run (C:\Users\joelp\Documents\repos\SharpLab\source\WebApp\node_modules\oldowan\dist\index.js:74:13)
    at Object.task.run (C:\Users\joelp\Documents\repos\SharpLab\source\WebApp\node_modules\oldowan\dist\index.js:74:13)
    at Object.build (C:\Users\joelp\Documents\repos\SharpLab\source\WebApp\node_modules\oldowan\dist\index.js:107:9)
task ts failed: task asm failed
task build failed: task ts failed
task start failed: task build failed
```

**Comment by ashmind** [comment]
```
Cannot read property 'split' of undefined
```

Hmm -- looking at the code it would seem like you are missing `source/WebApp/components/internal/codemirror/mode-asm-instructions.txt` for some reason. I'll have to add more logging to this. (might take a bit of time given current priorities)

**Comment by Meir017** [comment]
Try #1365
