### ISSUE TITLE
StringBuilder.Equals blocked

### ISSUE THREAD

**Issue by danmosemsft** [ashmind/SharpLab#561]
```
public static class Program {
    public static void Main() {
        var a = new System.Text.StringBuilder();
        bool x = a.Equals(a);
    }
}
```
```
Unbreakable.AssemblyGuardException: Member System.Text.StringBuilder.Equals is not allowed.
   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Executor.cs:line 70
   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in C:\projects\sharplab\source\Server\MirrorSharp\SlowUpdate.cs:line 110
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationTok
```
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmAZgAIBvAWACgLGLSTr6mOKA3AQygp4UAvBTwwA7swCMAOgAqMBBhkBlDFACWeAOYAhHBoA2AExhQAFAEoA3O06NgECIYoJhAmQFEAjjh6GAZ3MeGztGAF96cKA=

Not sure why you would block it.

**Comment by ashmind** [comment]
Thanks for reporting! Everything is blocked by default, and then I unblock ones people request after reviewing them.
This one is safe, so I'll allow it once I have time to do the change.

**Comment by jsk95** [comment]
`StringBuilder.Equals` has been allowlisted!
