### ISSUE TITLE
System.Delegate.get_Method is not allowed.

### ISSUE THREAD

**Issue by Turnerj** [ashmind/SharpLab#567]
Hey, just came across this while [testing a query](
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQygg5hG6CeADhACaoB2EA7gDQwgJzkA+AAgEwCMAsAFCsAGAAStOAOgBKEMABsIAYxgBLAPbkA3H0EjxAGSXkAjmICiAD0JJkyVeWSbeW9gGYhAbyGehfLyNeiANhEAFiEAWSgDAApRAQBtAF0hTCxkAEofLw9M309RAE4ogBUUGE4otLSHXK8C4tL2CqqcoQBfFpbLJQA3WAgdINihEuQyipa3Ft8AEQg5LD7koQBeIRiAVgAeFWAAKwUYAD40gEEAIQBhbb2Dw+qaoV6EIWAV5LEw3AALFRJ7mqeQnkb2AHygAGsIABxCCUBBKeSfGA/EhRGBECAqMAxTgCSr/XKsADsQLEADkoABbCAE9q8XydeG9GD9QI6YQjGCNDL0rJTWokmEwJEogCS5DAKjRGKxOLxNDWaRWhyE5yuO32ikOTXJVJpLTpvi6zNZnCCIt+4slQiFFpIVqlRQxQmQKkQ8ggTuICvMlhQNjUm1E7BVEAsVgD5B5vkmvIBmCE1ORvzeUTDfustjEZ1++GSyHC31+FygMhkvojtjSHyLf35eRJSZRYiFMLhCLtszABiUyjUFTBkLbEHhiNrUVd7s9GOacbaHTnxsWbKKqsumyK2qVVC+I/6q5AQkoVHGc9jDxEJOPwwqtL4rSAA==)

```
Unbreakable.AssemblyGuardException: Member System.Delegate.get_Method is not allowed.
   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
   at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-target-typed-new\sharplab\source\Server\Execution\Executor.cs:line 69
   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-features-target-typed-new\sharplab\source\Server\MirrorSharp\SlowUpdate.cs:line 110
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

You can simplify the code from my linked query to this and get the same issue:

```csharp
public static class Program {
    public static void Main() {
        Delegate a = (Action)Main;
        var b = a.Method;
    }
}
```

Happy to help with this if needed. 🙂

**Comment by ashmind** [comment]
Hi @Turnerj, thanks for reporting this! I didn't find time to look at it for a while, but this is now resolved by moving to a new Run model that does not block reflection anymore.

**Comment by Turnerj** [comment]
All good mate! I appreciate the work you've done on the project, thanks!
