### ISSUE TITLE
Overloaded static operators for struct type

### ISSUE THREAD

**Issue by jnyrup** [ashmind/SharpLab#582]
```cs
using System;

//public struct Value // does not work
public class Value
{
    public double V { get; }
    
    public Value(double v) => V = v;
    
    public static Value operator +(Value left, Value right) => new Value(left.V + right.V);
    
    public Value Add(Value other) => this + other;
}

public static class Program 
{
    public static void Main() 
    {
        var a = new Value(1);
        var b = new Value(2);
        var c = a.Add(b);
        
        Console.WriteLine(c.V); // this prints 3 as expected
    }
}
```

When changing the type of `Value` from `class` to `struct` I get an exception in Run mode.

```
Unbreakable.AssemblyGuardException: Method Value Value::Add(Value) performs pointer operations which cannot be validated.
   at Unbreakable.Internal.AssemblyValidation.PointerOperationValidator.ValidateInstruction(Instruction instruction, MethodDefinition method)
   at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-master\sharplab\source\Server\Execution\Executor.cs:line 69
   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-master\sharplab\source\Server\MirrorSharp\SlowUpdate.cs:line 110
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look when I have a moment.

**Comment by ashmind** [comment]
Hi @jnyrup, this is now resolved, and Run mode should be less restrictive overall.
