### ISSUE TITLE
IndexOutOfRangeException in ValidatingSourceTextWriter.ValidateBrackets

### ISSUE THREAD

**Issue by avonwyss** [ashmind/SharpLab#597]
The following C# method causes an error message in any result type:
```CS
    public static int Append(int hash, int value) {
        return Append(Append(Append(Append(hash, (byte)value), value>>8), value>>16), value>>24);
    }
```
https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgZgATIEzoMLoG8BYAKHXMw2QEYA2dMAO2HQEEAHdgU0ZgAomLABYBDAM5CoDZugBuIiAFcuASkKkKmzAHY2nHvw7defIwdP6ToiVL4AjAJ7BV8paqmvlAPi8AOFR4K3l50AXJBXD5YACwqANwaFAC+pCkkQA==

Full error:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SharpLab.Server.MirrorSharp.Guards.RoslynSourceTextGuard.ValidatingSourceTextWriter.ValidateBrackets(Char char, Char openBracket, Char closeBracket, Int32& nestingLevel, Int32[] adjacentPairCounts) in D:\a\SharpLab\SharpLab\source\Server\MirrorSharp\Guards\RoslynSourceTextGuard.cs:line 42
   at SharpLab.Server.MirrorSharp.Guards.RoslynSourceTextGuard.ValidatingSourceTextWriter.Write(Char char) in D:\a\SharpLab\SharpLab\source\Server\MirrorSharp\Guards\RoslynSourceTextGuard.cs:line 39
   at System.IO.TextWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at Microsoft.CodeAnalysis.Text.SourceText.Write(TextWriter writer, TextSpan span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Text.SourceText.Write(TextWriter textWriter, CancellationToken cancellationToken)
   at SharpLab.Server.MirrorSharp.Guards.RoslynSourceTextGuard.ValidateSourceText(SourceText sourceText) in D:\a\SharpLab\SharpLab\source\Server\MirrorSharp\Guards\RoslynSourceTextGuard.cs:line 25
   at MirrorSharp.Internal.Roslyn.RoslynSession.EnsureDocumentUpToDate()
   at MirrorSharp.Internal.Handlers.RequestInfoTipHandler.ExecuteForRoslynAsync(Int32 cursorPosition, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

**Comment by danmoseley** [comment]
Another variation
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmABgFgAoa2qgAkaecZwEs8N6BDegXnoAKdpwCUgiRICe9AFT0AXqPoA+FfQDMJZQGp6ARmXyEytZu0BuOi2osmdIA===

**Comment by ashmind** [comment]
Thanks for reporting -- I'll take a look when I have a moment.

**Comment by ashmind** [comment]
This is now resolved.
