### ISSUE TITLE
System.Numerics.BigInteger is not allowed in Run mode.

### ISSUE THREAD

**Issue by udaken** [ashmind/SharpLab#607]
BigInteger is similar to the integer numeric type, and is safe.
However, it is not allowed in sharplab.

```
Unbreakable.AssemblyGuardException: Type System.Numerics.BigInteger is not allowed.

   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)

   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference, Instruction instruction)

   at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)

   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)

   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)

   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)

   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session) in D:\a\SharpLab\SharpLab\source\Server\Execution\Executor.cs:line 69

   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\Server\MirrorSharp\SlowUpdate.cs:line 110

   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)

   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)

   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

**Comment by sitefortest** [comment]
What does this mean？ why not allowed? 
ArrayList is also not allowed, why?

**Comment by ashmind** [comment]
Thanks for reporting! While I agree it should be allowed, it's not fully safe and does need precautions.
A single user that allocates a sufficiently large `BigInteger` might cause SharpLab to run out of memory for all other users.

I am currently investigating an approach that will significantly reduce current constraints (and allow `BigInteger` and `ArrayList`).
If that approach does not work out, then I will look at `BigInteger` individually.

**Comment by ashmind** [comment]
Hi @udaken, BigInteger is now allowed (new Run mode no longer blocks specific types).

**Comment by udaken** [comment]
It's great. Sharplab is now more usable.
