### ISSUE TITLE
Unable to build `main` - System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by kkokosa** [ashmind/SharpLab#726]
When doing `dotnet tye run --watch -v Debug` the following exception is being thrown:

```
  System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.TypeLoadException: Method 'Rewrite' in type 'SharpLab.Server.Execution.Unbreakable.ArrayReturnRewriter' from assembly 'SharpLab.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
     at SharpLab.Server.Execution.Unbreakable.ApiPolicySetup.<>c.<SetupSystem>b__1_2(TypePolicy t)
     at Unbreakable.Policy.NamespacePolicy.Type(String typeName, ApiAccess access, Action`1 setup) in D:\a\Unbreakable\Unbreakable\[Core]\Policy\NamespacePolicy.cs:line 34
     at Unbreakable.Policy.NamespacePolicy.Type(Type type, ApiAccess access, Action`1 setup) in D:\a\Unbreakable\Unbreakable\[Core]\Policy\NamespacePolicy.cs:line 21
     at SharpLab.Server.Execution.Unbreakable.ApiPolicySetup.SetupSystem(NamespacePolicy namespacePolicy) in D:\github\tools\forks\SharpLab\source\Server\Execution\Unbreakable\ApiPolicySetup.cs:line 88
     at Unbreakable.ApiPolicy.Namespace(String namespace, ApiAccess access, Action`1 setup) in D:\a\Unbreakable\Unbreakable\[Core]\ApiPolicy.cs:line 27
     at SharpLab.Server.Execution.Unbreakable.ApiPolicySetup.CreatePolicy() in D:\github\tools\forks\SharpLab\source\Server\Execution\Unbreakable\ApiPolicySetup.cs:line 28
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at Unbreakable.Tools.PolicyReport.Program.GetPolicy(Assembly assembly, String factoryTypeName, String factoryMethodName) in D:\a\Unbreakable\Unbreakable\Tools.PolicyReport\Program.cs:line 191
     at Unbreakable.Tools.PolicyReport.Program.SafeMain(Arguments arguments) in D:\a\Unbreakable\Unbreakable\Tools.PolicyReport\Program.cs:line 36
     at Unbreakable.Tools.PolicyReport.Program.<>c__DisplayClass0_0.<Main>b__0(Arguments arguments) in D:\a\Unbreakable\Unbreakable\Tools.PolicyReport\Program.cs:line 20
D:\github\tools\forks\SharpLab\source\Server\Server.csproj(75,5): error MSB3073: The command "
D:\github\tools\forks\SharpLab\source\Server\Server.csproj(75,5): error MSB3073:         dotnet unbreakable-policy-report ^
D:\github\tools\forks\SharpLab\source\Server\Server.csproj(75,5): error MSB3073:             --assembly "D:\github\tools\forks\SharpLab\source\Server\bin\Debug\net5.0\SharpLab.Server.dll" ^
D:\github\tools\forks\SharpLab\source\Server\Server.csproj(75,5): error MSB3073:             --factory SharpLab.Server.Execution.Unbreakable.ApiPolicySetup ^
D:\github\tools\forks\SharpLab\source\Server\Server.csproj(75,5): error MSB3073:             --method CreatePolicy ^
D:\github\tools\forks\SharpLab\source\Server\Server.csproj(75,5): error MSB3073:             --output "D:\github\tools\forks\SharpLab\source\Server\Execution\Unbreakable\ApiPolicySetup.PolicyReport.txt"
D:\github\tools\forks\SharpLab\source\Server\Server.csproj(75,5): error MSB3073:     " exited with code -2146232828.

Build FAILED.
```

I'd love to help but not sure how.

**Comment by ashmind** [comment]
Interesting, thanks for reporting! As a workaround you can temporarily disable `_UpdatePolicyReport` target inside of `Server\Server.csproj` -- it's not essential unless you are actually changing the policy.

It is probably a versioning error, the global tool version is somehow incompatible with Unbreakable version -- I'll need to try out a clean build on my local. However since I am aiming to remove Unbreakable soon-ish, I might not prioritize this straight away.

**Comment by kkokosa** [comment]
Yep, I did it as you said, by disabling this target as a temporary workaround.

**Comment by ashmind** [comment]
Hi @kkokosa -- Unbreakable and related build steps were removed from .NET 6 project, so this should no longer be a problem.
Not sure if it might still be a problem for .NET Framework one, but that one should not run in tye anyway.
