### ISSUE TITLE
ReflectionTypeLoadException when disassembling F# discriminated union

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#736]
[I'm attempting to to see JIT Asm of a simple F# discriminated union:](https://sharplab.io/#v2:DYLgZgzgNALiCGEC2AfGBPADgUwAQGUALeHXAXgFgAoXW3FXAJWwGMZ4A7Ac2DwHswuAO4BLACYxCuELjDA+8GLgBUuXt0nTZ8xdTr1cAYREAnFr1wDcJ+GJEBXCFrkKYQA=)

```f#
type Shape =
    | Rectangle of width : float * length : float
    | Circle of radius : float
```

But SharpLab is showing the following exception:

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'Equals' in type 'Rectangle' from assembly '_, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'Equals' in type 'Circle' from assembly '_, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at SharpLab.Server.Decompilation.JitAsmDecompiler.ValidateStaticConstructors(Assembly assembly) in D:\a\SharpLab\SharpLab\source\Server\Decompilation\JitAsmDecompiler.cs:line 57
   at SharpLab.Server.Decompilation.JitAsmDecompiler.Decompile(CompilationStreamPair streams, TextWriter codeWriter) in D:\a\SharpLab\SharpLab\source\Server\Decompilation\JitAsmDecompiler.cs:line 38
   at SharpLab.Server.MirrorSharp.SlowUpdate.WriteResult(IFastJsonWriter writer, Object result, IWorkSession session) in D:\a\SharpLab\SharpLab\source\Server\MirrorSharp\SlowUpdate.cs:line 177
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.SendSlowUpdateAsync(IReadOnlyList`1 diagnostics, WorkSession session, Object extensionResult, ICommandResultSender sender, CancellationToken cancellationToken)
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
System.TypeLoadException: Method 'Equals' in type 'Rectangle' from assembly '_, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'Equals' in type 'Circle' from assembly '_, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by ashmind** [comment]
Thanks for reporting! I am tracking at #639 -- I remember I looked at it but could not figure it out quickly enough.
I'll revisit when I have a moment.

**Comment by svick** [comment]
Ok, in that case, I'm going to close this one.

**Comment by ashmind** [comment]
After some investigation, #639 is too generic looking at the logs, and has variety of other valid scenarios.
So I am going to suppress it in the generic case, and reopen this one for F# specifically.

**Comment by ashmind** [comment]
I have a feeling that this one is the same as https://stackoverflow.com/questions/58640268/unable-to-load-assemby-built-with-f-compiler-services-via-reflection -- which does not seem to have any answers yet.

I'll take a look, but based on my previous experience with F# compiler services any work in that area is extremely challenging.
If anyone has better skills in F# compiler services or can answer the StackOverflow question, pls feel free to pick up this one.
