### ISSUE TITLE
Container/Pipe broken on HTTP request attempt

### ISSUE THREAD

**Issue by 0x25CBFC4F** [ashmind/SharpLab#880]
Initially I tried this code:

```csharp
Console.WriteLine(new System.Net.Http.HttpClient().GetAsync("https://google.com").Result.Content.ReadAsStringAsync().Result);
```

I got this in return:

![image](https://user-images.githubusercontent.com/43248537/140933169-da2a5abb-d9a1-4919-8db0-c77eea30833b.png)

Then, after 15 seconds I tried this code:
```csharp
Console.WriteLine("test");
```

And got this in response:
```
System.Exception: Container host reported an error:
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ProtoBuf.ProtoWriter.StreamProtoWriter.TryFlush(State& state) in /_/src/protobuf-net.Core/ProtoWriter.Stream.cs:line 97
   at ProtoBuf.ProtoWriter.StreamProtoWriter.ImplEndLengthPrefixedSubItem(State& state, SubItemToken token, PrefixStyle style) in /_/src/protobuf-net.Core/ProtoWriter.Stream.cs:line 409
   at ProtoBuf.Meta.TypeModel.SerializeWithLengthPrefix(Stream dest, Object value, Type type, PrefixStyle style, Int32 fieldNumber, SerializationContext context) in /_/src/protobuf-net.Core/Meta/TypeModel.cs:line 693
   at SharpLab.Container.Manager.Internal.ExecutionProcessor.ExecuteInContainerAsync(ActiveContainer container, Byte[] assemblyBytes, Byte[] outputBufferBytes, Boolean includePerformance, Boolean isWarmup, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\Container.Manager\Internal\ExecutionProcessor.cs:line 63
   at SharpLab.Container.Manager.Internal.ExecutionManager.ExecuteAsync(String sessionId, Byte[] assemblyBytes, Byte[] outputBufferBytes, Boolean includePerformance, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\Container.Manager\Internal\ExecutionManager.cs:line 62
   at SharpLab.Container.Manager.Endpoints.ExecutionEndpoint.ExecuteAsync(HttpContext context) in D:\a\SharpLab\SharpLab\source\Container.Manager\Endpoints\ExecutionEndpoint.cs:line 89
   at SharpLab.Server.Execution.Container.ContainerClient.ExecuteAsync(String sessionId, Stream assemblyStream, Boolean includePerformance, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\Server\Execution\Container\ContainerClient.cs:line 40
   at SharpLab.Server.Execution.ContainerExecutor.ExecuteAsync(CompilationStreamPair streams, IWorkSession session, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\Server\Execution\ContainerExecutor.cs:line 59
   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\Server\MirrorSharp\SlowUpdate.cs:line 137
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 40
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 118
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 73
```

Known problem or a new bug? :)

**Comment by ashmind** [comment]
Good catch, thanks for reporting! "Pipe is broken" is not expected in this case -- I'll need to improve this one specifically.

However in general network requests will cause container timeout, as all network requests are currently blocked inside the Run environment for security reasons, and the way they are blocked does not fail fast.
