### ISSUE TITLE
Problems with localhost deployment

### ISSUE THREAD

**Issue by mopinon** [ashmind/SharpLab#886]
Hi!

I have similar problems with deployment #538 , I tried all the steps described there.
I tried all the actions described there, but the problem with `System.ComponentModel.Win32Exception` remains. 

My environment:
- Windows 10 21H1
- node js 16.13.0
- npm 8.1.3

Algorithm of my actions:
1. Cloned the repository
2. Run `sl setup` 
```
SharpLab setup done.
Run sl run to start.
```
3. Run `sl run`
```
sl run
Opening new window for initial wait
Loading Application Details...
Launching Tye Host...

[18:15:10 INF] Executing application from C:\Projects\SharpLab\tye.yaml
[18:15:10 INF] Dashboard running on http://127.0.0.1:8000
[18:15:11 INF] Building projects
[18:15:13 INF] Launching service azurite_71bc70c7-4: pwsh -Command "azurite"
[18:15:13 INF] Launching service webapp-assets_a425ec3f-9: pwsh -Command "npm run start"
[18:15:13 INF] Launching service container-manager_74955c95-a: C:\Projects\SharpLab\source\Container.Manager\bin\Debug\net6.0\SharpLab.Container.Manager.exe
[18:15:13 INF] Launching service webapp-server_12d16301-0: C:\Projects\SharpLab\source\WebApp.Server\bin\Debug\net6.0\SharpLab.WebApp.Server.exe
[18:15:13 ERR] Failed to launch process for service azurite_71bc70c7-4
System.ComponentModel.Win32Exception (267): The folder name is incorrect.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 113
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
[18:15:13 INF] webapp-assets_a425ec3f-9 running on process id 5808
[18:15:13 INF] Replica webapp-assets_a425ec3f-9 is moving to a ready state
[18:15:14 INF] Selected process 5808.
[18:15:14 INF] Listening for event pipe events for webapp-assets_a425ec3f-9 on process id 5808
[18:15:14 INF] Event pipe collection completed for webapp-assets_a425ec3f-9 on process id 5808
[18:15:14 INF] container-manager_74955c95-a running on process id 1944 bound to http://localhost:44400
[18:15:14 INF] Replica container-manager_74955c95-a is moving to a ready state
[18:15:14 INF] watch: container-manager_74955c95-a Started
[18:15:15 INF] Selected process 1944.
[18:15:15 INF] Listening for event pipe events for container-manager_74955c95-a on process id 1944
[18:15:16 INF] webapp-server_12d16301-0 running on process id 2672 bound to http://localhost:44100
[18:15:16 INF] Replica webapp-server_12d16301-0 is moving to a ready state
[18:15:16 INF] watch: webapp-server_12d16301-0 Started
[18:15:16 INF] Selected process 2672.
[18:15:16 INF] Listening for event pipe events for webapp-server_12d16301-0 on process id 2672
[18:15:16 INF] Tye Host is stopping...
[18:15:19 INF] Event pipe collection completed for container-manager_74955c95-a on process id 1944
[18:15:19 INF] Event pipe collection completed for webapp-server_12d16301-0 on process id 2672
[18:15:19 INF] container-manager_74955c95-a process exited with exit code -1073741510
[18:15:19 INF] webapp-server_12d16301-0 process exited with exit code -1073741510
[18:15:19 INF] watch: container-manager_74955c95-a Exited
[18:15:19 ERR] watch: Exited with error code Microsoft.Tye.ProcessResult
[18:15:19 INF] webapp-assets_a425ec3f-9 process exited with exit code -1
[18:15:19 WRN] Waiting for a file to change before restarting dotnet...
```

 I want to deploy SharpLab on a local network by reworking the policy.

Thanks for the good tool!

**Comment by ashmind** [comment]
Thanks for reporting!

For this specific error:
```
System.ComponentModel.Win32Exception (267): The folder name is incorrect.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 113
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
```

It's likely that I need to add a step to create an empty `!azurite` folder under the solution root to `sl setup`.
In the meantime, please try creating that folder manually.

Not sure if there are other issues happening as well.

**Comment by mopinon** [comment]
Thank you for your  help!!
It's not that easy)

> Not sure if there are other issues happening as well.

After `sl setup`
```
Installing node modules
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile Error: ENOENT: no such file or directory, open 'C:\Projects\SharpLab\source\package.json'
npm WARN old lockfile  Could not fetch metadata for source@file:C:\Projects\SharpLab\source [Error: ENOENT: no such file or directory, open 'C:\Projects\SharpLab\source\package.json'] {
npm WARN old lockfile   errno: -4058,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: 'C:\\Projects\\SharpLab\\source/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open 'C:\Projects\SharpLab\source\package.json'
npm WARN old lockfile  Could not fetch metadata for mirrorsharp@file:../.. [Error: ENOENT: no such file or directory, open 'C:\Projects\SharpLab\source\package.json'] {
npm WARN old lockfile   errno: -4058,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: 'C:\\Projects\\SharpLab\\source/package.json'
npm WARN old lockfile }
npm WARN deprecated request-promise-native@1.0.8: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
```

After `sl run'
```
[15:43:23 INF] Listening for event pipe events for webapp-server_3a905fbb-b on process id 12104
[15:43:26 INF] Event pipe collection completed for container-manager_7eaf62d2-a on process id 11412
[15:43:26 INF] container-manager_7eaf62d2-a process exited with exit code -532462766
[15:43:26 ERR] watch: Exited with error code Microsoft.Tye.ProcessResult
[15:43:26 WRN] Waiting for a file to change before restarting dotnet...
[15:43:56 INF] webapp-assets_61c2914d-8 process exited with exit code 1
```

Logs for container-manager:
```
[container-manager_7eaf62d2-a]:C:\Projects\SharpLab\source\Container.Manager\bin\Debug\net6.0\SharpLab.Container.Manager.exe
[container-manager_7eaf62d2-a]: Unhandled exception. System.Exception: Required environment variable SHARPLAB_CONTAINER_HOST_AUTHORIZATION_TOKEN was not provided.
[container-manager_7eaf62d2-a]: at SharpLab.Container.Manager.Startup.ConfigureServices(IServiceCollection services) in C:\Projects\SharpLab\source\Container.Manager\Startup.cs:line 33
[container-manager_7eaf62d2-a]: at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[container-manager_7eaf62d2-a]: at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[container-manager_7eaf62d2-a]: at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
[container-manager_7eaf62d2-a]: at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
[container-manager_7eaf62d2-a]: at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
[container-manager_7eaf62d2-a]: at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
[container-manager_7eaf62d2-a]: at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
[container-manager_7eaf62d2-a]: at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
[container-manager_7eaf62d2-a]: at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
[container-manager_7eaf62d2-a]: at Microsoft.Extensions.Hosting.HostBuilder.Build()
[container-manager_7eaf62d2-a]: at SharpLab.Container.Manager.Program.Main(String[] args) in C:\Projects\SharpLab\source\Container.Manager\Program.cs:line 11
```

Logs for webapp-assets:
```
[webapp-assets_61c2914d-8]:pwsh -Command "npm run start"
[webapp-assets_61c2914d-8]:
[webapp-assets_61c2914d-8]: > sharplab@0.0.0 start
[webapp-assets_61c2914d-8]: > ts-node-script ./scripts.ts start --watch
[webapp-assets_61c2914d-8]:
[webapp-assets_61c2914d-8]: task start starting...
[webapp-assets_61c2914d-8]: task build starting...
[webapp-assets_61c2914d-8]: task deps starting...
[webapp-assets_61c2914d-8]: task deps:check-duplicates starting...
[webapp-assets_61c2914d-8]: task less starting...
[webapp-assets_61c2914d-8]: task ts starting...
[webapp-assets_61c2914d-8]: task ts:asm-regex starting...
[webapp-assets_61c2914d-8]: task icons starting...
[webapp-assets_61c2914d-8]: task manifest starting...
[webapp-assets_61c2914d-8]: task html starting...
[webapp-assets_61c2914d-8]: task latest starting...
[webapp-assets_61c2914d-8]: task latest completed [91ms]
[webapp-assets_61c2914d-8]: task manifest completed [94ms]
[webapp-assets_61c2914d-8]: task ts:asm-regex completed [96ms]
[webapp-assets_61c2914d-8]: task ts:lint starting...
[webapp-assets_61c2914d-8]: task less failed:
[webapp-assets_61c2914d-8]: [LessError: '../../node_modules/mirrorsharp/mirrorsharp.less' wasn't found. Tried - C:\Projects\SharpLab\source\WebApp\node_modules\mirrorsharp\mirrorsharp.less,..\..\node_modules\mirrorsharp\mirrorsharp.less] {
[webapp-assets_61c2914d-8]: stack: undefined,
[webapp-assets_61c2914d-8]: type: 'File',
[webapp-assets_61c2914d-8]: filename: 'C:\\Projects\\SharpLab\\source\\WebApp\\node_modules\\mirrorsharp-codemirror-6-preview\\mirrorsharp.less',
[webapp-assets_61c2914d-8]: index: undefined,
[webapp-assets_61c2914d-8]: line: null,
[webapp-assets_61c2914d-8]: column: -1,
[webapp-assets_61c2914d-8]: callLine: NaN,
[webapp-assets_61c2914d-8]: callExtract: undefined,
[webapp-assets_61c2914d-8]: extract: [ undefined, undefined, undefined ]
[webapp-assets_61c2914d-8]: }
[webapp-assets_61c2914d-8]: task build failed: task less failed
[webapp-assets_61c2914d-8]: task start failed: task build failed
```
Logs for webapp-server:
Application startup failed: could not load index.html from the assets storage.
```
[webapp-server_3a905fbb-b]:C:\Projects\SharpLab\source\WebApp.Server\bin\Debug\net6.0\SharpLab.WebApp.Server.exe
[webapp-server_3a905fbb-b]: info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
[webapp-server_3a905fbb-b]: Start processing HTTP request GET http://localhost:44200/latest
[webapp-server_3a905fbb-b]: info: System.Net.Http.HttpClient.Default.ClientHandler[100]
[webapp-server_3a905fbb-b]: Sending HTTP request GET http://localhost:44200/latest
[webapp-server_3a905fbb-b]: fail: SharpLab.WebApp.Server.Assets.IndexHtmlEndpoints[0]
[webapp-server_3a905fbb-b]: Failed to load initial index.html. Retrying...
[webapp-server_3a905fbb-b]: System.Net.Http.HttpRequestException: Connection failed because the endpoint rejected the connection request. (localhost:44200)
[webapp-server_3a905fbb-b]: ---> System.Net.Sockets.SocketException (10061): Connection not established because the endpoint rejected the connection request.
```
![image](https://user-images.githubusercontent.com/58467666/141787389-2c0e1c66-e468-43b8-bfa9-3ecb36deb3f6.png)

**Comment by htranou** [comment]
I had some difficulties to run locally too. The following additional steps were enough to fix them for me:

in Container.Manager, copy .env.template to .env. That should fix the SHARPLAB_CONTAINER_HOST_AUTHORIZATION_TOKEN error. Not sure why setup doesn't do like for webapp.

Container were closing immediately resulting in broken pipe error. I had to uncomment the code in the InitialSetup in Fragile. (probably don't see it if you're not on a clean repo). Seems like the capability SID was missing access to the output directory (process was exiting with error 0x80008085).

Finally, had to run some npm install in webapp-assets. Out of my head, needed tsc, eslint, http-server and probably couple others. Not sure why sl setup didn't install them.

Hope this helps.

**Comment by Ali94k** [comment]
Hi!

I also have similar issue. I have tried to run locally with the commands `dotnet tye run --watch` and `.\sl.bat run` , but unfortunately, I wasn't able to achieve success with either of cases.

content of .env.template to .env in Container.Manager is identical.

Could you kindly provide insights into the potential causes of this error?

webapp-server log:

```
[webapp-server_39499477-d]:C:\RiderProjects\SharpLab\source\WebApp.Server\bin\Debug\net7.0\SharpLab.WebApp.Server.exe
[webapp-server_39499477-d]: info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
[webapp-server_39499477-d]: Start processing HTTP request GET http://localhost:44200/latest
[webapp-server_39499477-d]: info: System.Net.Http.HttpClient.Default.ClientHandler[100]
[webapp-server_39499477-d]: Sending HTTP request GET http://localhost:44200/latest
[webapp-server_39499477-d]: fail: SharpLab.WebApp.Server.Assets.IndexHtmlEndpoints[0]
[webapp-server_39499477-d]: Failed to load initial index.html. Retrying...
[webapp-server_39499477-d]: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:44200)
[webapp-server_39499477-d]: ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
[webapp-server_39499477-d]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
```
