### ISSUE TITLE
main is broken

### ISSUE THREAD

**Issue by 333fred** [ashmind/SharpLab#922]
Attempting to use the `main` branch currently fails with this exception:

```
System.AggregateException: One or more errors occurred. (No export was found for the contract 'IVSTypeScriptFormattingServiceImplementation'

 -> required by import 'impl' of part 'VSTypeScriptFormattingService'

 -> required by import 'value' of part 'Lazy<ILanguageService, LanguageServiceMetadata>'

 -> required by import 'item' of part 'Lazy`2[]'

 -> required by initial request for contract 'IEnumerable<Lazy<ILanguageService, LanguageServiceMetadata>> { IsImportMany = True }') (No export was found for the contract 'IVSTypeScriptFormattingServiceImplementation'

 -> required by import 'impl' of part 'VSTypeScriptFormattingService'

 -> required by import 'value' of part 'Lazy<ILanguageService, LanguageServiceMetadata>'

 -> required by import 'item' of part 'Lazy`2[]'

 -> required by initial request for contract 'IEnumerable<Lazy<ILanguageService, LanguageServiceMetadata>> { IsImportMany = True }')

 ---> System.Composition.Hosting.CompositionFailedException: No export was found for the contract 'IVSTypeScriptFormattingServiceImplementation'

 -> required by import 'impl' of part 'VSTypeScriptFormattingService'

 -> required by import 'value' of part 'Lazy<ILanguageService, LanguageServiceMetadata>'

 -> required by import 'item' of part 'Lazy`2[]'

 -> required by initial request for contract 'IEnumerable<Lazy<ILanguageService, LanguageServiceMetadata>> { IsImportMany = True }'

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract contract)

   at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract exportKey, ExportDescriptor& defaultForExport)

   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)

   at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract contract, Object& export)

   at System.Composition.CompositionContextExtensions.SatisfyImportsInternal(CompositionContext exportProvider, Object objectWithLooseImports, AttributedModelProvider conventions)

   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Microsoft.CodeAnalysis.Host.Mef.IMefHostExportProvider.GetExports[TExtension,TMetadata]() in /_/src/Workspaces/Core/Portable/Workspace/Host/Mef/MefHostServices.cs:line 69

   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices..ctor(MefWorkspaceServices workspaceServices, String language) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/MefLanguageServices.cs:line 25

   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.<>c.<GetLanguageServices>b__21_0(String languageName, MefWorkspaceServices self) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/MefWorkspaceServices.cs:line 163

   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue,TArg](ImmutableDictionary`2& location, TKey key, Func`3 valueFactory, TArg factoryArgument)

   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetLanguageServices(String languageName) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/MefWorkspaceServices.cs:line 160

   at Microsoft.CodeAnalysis.SolutionState.AddProject(ProjectInfo projectInfo) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 527

   at Microsoft.CodeAnalysis.Solution.AddProject(ProjectInfo projectInfo) in /_/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs:line 317

   at MirrorSharp.Internal.Roslyn.RoslynSession.CreateProjectAndOpenNewDocument(Workspace workspace, ProjectInfo projectInfo, SourceText sourceText) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynSession.cs:line 75

   at MirrorSharp.Internal.Roslyn.RoslynSession..ctor(SourceText sourceText, ProjectInfo projectInfo, MefHostServices hostServices, ImmutableArray`1 analyzers, ImmutableDictionary`2 codeFixProviders, ImmutableArray`1 signatureHelpProviders, ILanguageSessionExtensions extensions) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynSession.cs:line 67

   at MirrorSharp.Internal.Roslyn.RoslynLanguageBase.CreateSession(String text, ILanguageSessionExtensions extensions) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynLanguageBase.cs:line 70

   at MirrorSharp.Internal.Handlers.RequestInfoTipHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Handlers\RequestInfoTipHandler.cs:line 16

   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 118

   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 73

   --- End of inner exception stack trace ---

 ---> (Inner Exception #1) System.Composition.Hosting.CompositionFailedException: No export was found for the contract 'IVSTypeScriptFormattingServiceImplementation'

 -> required by import 'impl' of part 'VSTypeScriptFormattingService'

 -> required by import 'value' of part 'Lazy<ILanguageService, LanguageServiceMetadata>'

 -> required by import 'item' of part 'Lazy`2[]'

 -> required by initial request for contract 'IEnumerable<Lazy<ILanguageService, LanguageServiceMetadata>> { IsImportMany = True }'

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency dependency, HashSet`1 checked, Stack`1 checking)

   at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract contract)

   at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract exportKey, ExportDescriptor& defaultForExport)

   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)

   at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract contract, Object& export)

   at System.Composition.CompositionContextExtensions.SatisfyImportsInternal(CompositionContext exportProvider, Object objectWithLooseImports, AttributedModelProvider conventions)

   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Microsoft.CodeAnalysis.Host.Mef.IMefHostExportProvider.GetExports[TExtension,TMetadata]() in /_/src/Workspaces/Core/Portable/Workspace/Host/Mef/MefHostServices.cs:line 69

   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices..ctor(MefWorkspaceServices workspaceServices, String language) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/MefLanguageServices.cs:line 25

   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.<>c.<GetLanguageServices>b__21_0(String languageName, MefWorkspaceServices self) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/MefWorkspaceServices.cs:line 163

   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue,TArg](ImmutableDictionary`2& location, TKey key, Func`3 valueFactory, TArg factoryArgument)

   at Microsoft.CodeAnalysis.Host.Mef.MefWorkspaceServices.GetLanguageServices(String languageName) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Workspace/Mef/MefWorkspaceServices.cs:line 160

   at Microsoft.CodeAnalysis.SolutionState.AddProject(ProjectInfo projectInfo) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 527

   at Microsoft.CodeAnalysis.Solution.AddProject(ProjectInfo projectInfo) in /_/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs:line 317

   at MirrorSharp.Internal.Roslyn.RoslynSession.CreateProjectAndOpenNewDocument(Workspace workspace, ProjectInfo projectInfo, SourceText sourceText) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynSession.cs:line 75

   at MirrorSharp.Internal.Roslyn.RoslynSession..ctor(SourceText sourceText, ProjectInfo projectInfo, MefHostServices hostServices, ImmutableArray`1 analyzers, ImmutableDictionary`2 codeFixProviders, ImmutableArray`1 signatureHelpProviders, ILanguageSessionExtensions extensions) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynSession.cs:line 67

   at MirrorSharp.Internal.Roslyn.RoslynLanguageBase.CreateSession(String text, ILanguageSessionExtensions extensions) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynLanguageBase.cs:line 70

   at MirrorSharp.Internal.WorkSession.GetText() in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\WorkSession.cs:line 51

   at SharpLab.Server.Integration.Azure.ApplicationInsightsMonitor.Exception(Exception exception, IWorkSession session, IDictionary`2 extras) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\Server\Integration\Azure\ApplicationInsightsMonitor.cs:line 33

   at SharpLab.Server.MirrorSharp.MonitorExceptionLogger.LogException(Exception exception, IWorkSession session) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\Server\MirrorSharp\MonitorExceptionLogger.cs:line 20

   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 73<---
```

**Comment by bernd5** [comment]
https://github.com/dotnet/roslyn/issues/58841

**Comment by jasonmalinowski** [comment]
This'll be fixed by https://github.com/dotnet/roslyn/pull/58940

**Comment by bernd5** [comment]
@jasonmalinowski could you or work on this with a higher priority?
(or Sam...)

**Comment by sharwell** [comment]
The fix for this is already merged into Roslyn.

**Comment by bernd5** [comment]
@ashmind could you update the rosyln main branch to the current version?

**Comment by ashmind** [comment]
Thanks for the ping -- this is normally updated automatically, but I see there is an issue that requires manual resolution (needs version upgrade on one of the dependencies) -- I'll take a look now.

**Comment by ashmind** [comment]
OK `main` seems to be OK now -- please let me know if you are still seeing any issues, otherwise I'll close the ~incident~ ticket sometime later today.

**Comment by bernd5** [comment]
Thanks, it seems to work now 👍

**Comment by 333fred** [comment]
Thanks ashmind for all your work on sharplab. We really appreciate it.
