### ISSUE TITLE
intermittent TypeInitializationException when using main branch

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#947]
This seems to happen for some submissions but not others. Refreshing the page often makes the issue go away. This doesn't occur for branches more than a few months old, e.g. the Pattern Matching on 'ReadOnlySpan<char>' branch.

```
System.TypeInitializationException: The type initializer for 'MirrorSharp.Internal.Reflection.RoslynReflection' threw an exception.
 ---> System.ArgumentException: Incorrect number of arguments for constructor
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount(MethodBase method, ExpressionType nodeKind, Int32 count, ParameterInfo[] pis)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at MirrorSharp.Internal.Reflection.RoslynReflection.BuildDelegateForConstructorSlow[TFunc](ConstructorInfo constructor) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Reflection\RoslynReflection.cs:line 128
   at MirrorSharp.Internal.Reflection.RoslynReflection.BuildDelegateForNewWorkspaceAnalyzerOptionsSlow() in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Reflection\RoslynReflection.cs:line 110
   at MirrorSharp.Internal.Reflection.RoslynReflection..cctor() in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Reflection\RoslynReflection.cs:line 28
   --- End of inner exception stack trace ---
   at MirrorSharp.Internal.Roslyn.RoslynSession.GetDiagnosticsAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynSession.cs:line 100
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 40
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 118
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 73
```

**Comment by canton7** [comment]
This is happening constantly for me now.

**Comment by ashmind** [comment]
Thanks for reporting -- it is something I have started working on in #941 and #942, but it turned out to be quite a bit more challenging than I initially expected, and I temporarily ran out of open source motivation.

I'll try to look at it further this week.

**Comment by ashmind** [comment]
This should be resolved now -- please let me know if you see any further issues.
