### ISSUE TITLE
MissingFieldException in main branch

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#994]
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzguATEBqAPgAQCYBGAWACh8BmAAiJoGEaBvCm9u2/AFhoFkAFAEoWbDgF8K4oA

Note that the Default branch is working, but not main. It seems that it's sometimes necessary to make edits before the error occurs.

Stack trace:

```
System.MissingFieldException: Field not found: 'Microsoft.CodeAnalysis.Diagnostics.IdeAnalyzerOptions.Default'.
   at MirrorSharp.Internal.Roslyn43.WorkspaceAnalyzerOptionsInternals.New(AnalyzerOptions options, Solution solution)
   at MirrorSharp.Internal.Roslyn.RoslynSession.GetDiagnosticsAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Roslyn\RoslynSession.cs:line 103
   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 39
   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 118
   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\!roslyn-branches\dotnet-main\sharplab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 73
```

**Comment by ashmind** [comment]
Thanks for reporting! I'll look to fix this this soon.

**Comment by RikkiGibson** [comment]
fwiw, I have not been able to reproduce this recently. It's possible the issue has worked itself out :)

**Comment by ashmind** [comment]
Thanks! I wasn't able to reproduce either, so I'll close this one for now.
